# Generated by Django 5.1.2 on 2024-10-16 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('second_name', models.CharField(blank=True, max_length=20)),
                ('payment', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('coment', models.TextField(blank=True, max_length=100)),
                ('yare', models.CharField(blank=True, max_length=5)),
                ('month', models.CharField(blank=True, max_length=10)),
                ('day', models.CharField(blank=True, max_length=2)),
                ('sportCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academapp.catigory')),
            ],
        ),
    ]
