# Generated by Django 5.1.2 on 2024-10-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academapp', '0002_alter_worker_sportcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
