# Generated by Django 5.1.2 on 2024-10-16 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academapp', '0003_alter_catigory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catigory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='sportCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='academapp.catigory'),
        ),
    ]
