# Generated by Django 5.1.2 on 2024-10-16 15:07

import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='sportCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.fields.CharField, to='academapp.catigory'),
        ),
    ]
