# Generated by Django 5.1.2 on 2024-10-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academapp', '0004_alter_catigory_name_alter_worker_sportcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='coment',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='worker',
            name='day',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='worker',
            name='month',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='worker',
            name='payment',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='yare',
            field=models.CharField(max_length=5),
        ),
    ]
